// Public configuration only. Never use a secret or service-role key.
window.EPOCHA_CONFIG = {
  "supabaseUrl": "https://wgmhrtdkudjhsuchnycw.supabase.co",
  "publishableKey": "sb_publishable_QIgEf6SkLTUjwPf7mJ2n9w_PNCi3Qzj",
  "eventId": "korcos-2026",
  "questions": {
    "E": [
      "Think about a time when you understood what a student, parent or colleague was afraid of behind their push for top scores. How did that understanding impact your practice?",
      "How do you stay attuned to signs of burnout in students or colleagues while also delivering a demanding workload, and what do you do when those two pull against each other?",
      "When students or parents resist inquiry-based learning, what do you think they are protecting, and how could you acknowledge that before asking them to change?",
      "How do you notice and care for your own stress while carrying both institutional and parental expectations?",
      "How do you make sense of parent expectations that come from a different educational culture than your own?",
      "Think about a misunderstanding between colleagues from different countries about teaching or communication, and what helped you see the other view.",
      "How do you recognise the stress of students who are caught between home-country, Korean, and school expectations?",
      "How do you show empathy to colleagues who are under strain, and what makes that hard in a busy school culture?",
      "Think  about a time when someone really understood what was going on for you in a learning or school situation. What did they do that helped?",
      "Think  about a time when you misread someone at school (a student, parent, teacher, or leader) and later saw things differently. What changed your view?",
      "Think  about a moment in your daily life, outside school, that makes learning harder or easier for you or someone close to you.",
      "What is one thing about another role's reality (student, parent, teacher, administrator) that you understand better now than when you began?",
      "Think  about a time when you moved beyond being kind to a student and actually understood their experience. What changed in how you acted?",
      "How does believing that someone's behaviour has causes, such as their history, brain, or circumstances, change how you respond to them?",
      "What would it take for neurodivergent students, or students who feel different in other ways, to feel celebrated in your school and not only accommodated?",
      "Which students in your setting might not feel safe being fully themselves, and how would you know?",
      "How do you help young people recognise and manage their feelings, and what have you learned from how they teach you?",
      "Think  about a time when being in a diverse group was not enough to create real understanding. What was missing?"
    ],
    "P": [
      "Who in your network (other schools, university admissions staff, local offices of education, cram school contacts) have you drawn on to solve a problem, and what did the relationship make possible?",
      "Think about a time when full presence in a conversation with a student, even five minutes of undivided attention, mattered more than a solution.",
      "What would a stronger relationship with parents, hagwon tutors, or university admissions offices look like?",
      "What helps newly arrived students and colleagues feel they belong within the first weeks?",
      "Think about a connection you have made with Korean society, language, or community beyond the school gate, and what it taught you.",
      "How do you stay fully present with students when your own attention is pulled by assessment deadlines, reporting, and admissions?",
      "Who in your wider network (other international schools, local schools, community organisations) could you learn from or work with more?",
      "What rituals or routines in your setting create real human connection, and which are just administrative habit?",
      "Think  about a time in school when you felt fully seen, heard, and that you belonged. What made it possible?",
      "Think  about a time when you were physically in a room but not really present, or felt unseen. What was happening?",
      "Think  about a tradition, ritual, or relationship from your culture or family that shapes how you connect with others when learning.",
      "Who is usually not in the room when decisions about learning are made, and how could you connect with them?",
      "Where in your school do silos stop people from sharing what they know, and who could take the first step in bridging them?",
      "How do the arts, drama, or play help people in your community feel present with each other in ways that screens do not?",
      "In which situations might your graduates be academically strong but socially or culturally unprepared, and what could the school do about it?"
    ],
    "O": [
      "Think about a time when you had to balance local tests or admissions requirements, parent expectations, and holistic IB learning. What values guided you?",
      "Where have you seen inconsistent benchmarks between assessment and Korean or bilingual instruction, and what did you do about it?",
      "How do you help students form and defend their own views in a context that often rewards the expected answer?",
      "How do you decide which cultural assumptions in your own teaching to keep, question, or adapt in your school setting?",
      "When have you spoken up about workload, wellbeing, or fairness in assessment, and what was the result?",
      "How do you advise a student when the path that fits their identity and wellbeing differs from the one their family hopes for?",
      "Describe a recent decision where the AI pointed one way but your professional judgment pointed another. How did you resolve it?",
      "What ethical dilemmas come up regularly in your work (assessment fairness, privacy, student wellbeing), and how do you navigate them?",
      "When did you last change your mind about something important in your practice, and what prompted it?",
      "Think  about a time when you disagreed with what was expected of you in school, and how you decided what to do.",
      "Think  about a time when someone trusted your judgment, or you had to trust someone else's, in a decision about learning.",
      "Think  about a values-based choice you or a family made about education that others might not have understood.",
      "How can you disagree respectfully on something like discipline, homework, or technology and still keep learning from each other?",
      "When rules change, whether in university admissions, technology, or school policy, how do you decide what to hold to and what to adapt?",
      "A phone-free policy is a values-based decision as well as a practical one. What values would you want to guide it, and who should have a voice in making it?",
      "How does your school measure intercultural development, as opposed to counting the nationalities in the room?"
    ],
    "C": [
      "Think about a creative approach you used to make inquiry feel safe and worthwhile to students used to rote learning.",
      "What low-cost, practical ways have you found to support under-resourced or newly certified teachers when training time/budget is limited?",
      "What ideas from Korean educational or cultural traditions could strengthen inquiry-based learning rather than compete with it?",
      "Think about a way you have used the diversity of your classroom as a resource for learning.",
      "How have you adapted inquiry-based learning to students who have experienced very different schooling systems?",
      "How could you design transitions (arriving, leaving, changing programmes) so they become learning experiences rather than disruptions?",
      "If you could redesign your school week to protect time for wellbeing and reflection, or reduce pressure without lowering ambition, what would change, and how could you prototype and test one change over two weeks?",
      "Think  about a time when you learned something through play, making, struggle, or an unexpected, unconventional approach that stayed with you.",
      "Think  about a time when you or someone you know found a creative solution to a barrier to learning (time, money, language, distance, or family responsibilities).",
      "Think  about a story, song, craft, or practice from your culture that taught you something important.",
      "If you designed a learning experience together that honoured everyone in this the room, what would be in it?",
      "Where in your current practice are you following a routine that no longer serves learners, and what might replace it (a game, a drawing, a song, a prototype)?",
      "What would you design if you had no constraints on time, budget, or curriculum?",
      "How do you draw ideas from outside education (arts, industry, other cultures) into your work?",
      "What does creative work look like for you personally, and how do you protect time for it?",
      "Where could you design productive friction into learning (a challenge, a disagreement, a problem without a clear answer) instead of smoothing it away?",
      "How could the arts help your school make inclusion real in practice, not just in policy?",
      "How do students from different cultures approach the same problem differently, and how could you use those differences to deepen learning?"
    ],
    "H": [
      "Think about a moment when a student, parent, or colleague shifted from scepticism to trust in the IB approach. What did you do to sustain hope through the slow part?",
      "How do you share a clear vision for the programme with colleagues who are tired or sceptical during rapid expansion?",
      "When have you led or influenced change, with or without formal authority, to improve assessment alignment, student wellbeing, or teacher support? What made people willing to follow?",
      "What is one realistic step you could take this term to move your school closer to a healthy balance between rigour and wellbeing?",
      "How do you share a vision of \"international mindedness\" in everyday life?",
      "What future do you hope the young people in your life will be able to build, and how does your daily work or role contribute to it?",
      "How do you sustain hope for a student or team when progress is slow or setbacks pile up?",
      "Think  about a person who believed in you when you doubted yourself, and what they did or said.",
      "What is one small commitment your team can make this month to encourage youth leadership and civic engagement into our own setting?",
      "Think  about a time when students took real action on something that mattered to them, and what your role was in making that possible.",
      "Where do students in your school have genuine say in decisions, and where is the agency more symbolic than real?",
      "A mindful school culture is often described as \"an inside job.\" What would need to change in you before it could change in your school?",
      "Think of an idea you have been carrying from \"What if?\" and are stuck on in the \"messy middle.\" What is holding it back, who could help, and what small piece of action research could you run this term to test it?",
      "What would it look like for your students to leave with the ability to listen across difference as well as achieve strong results?"
    ],
    "A": [
      "How do students feel about AI in their schoolwork (relief, pressure, shame, fear of being accused), and how do you know?",
      "How might AI add to or reduce the pressure students already feel, and what could you do about it?",
      "How do you keep hope alive for students who fear AI will make their effort or their future less valuable?",
      "Think about a time when AI saved you time or effort, and what you chose to do with the time that was freed up. Did it go to people?",
      "How does AI reduce your workload in a way that leaves more room for creative teaching?",
      "Think about a time when AI sparked an idea for you or a student, and one where it flattened or narrowed your thinking.",
      "Think about a time when technology, including AI, pulled your attention away from the person in front of you, and a time when it freed you to be more present.",
      "Where do you draw the line between acceptable AI support and academic misconduct in assessed work such as the Extended Essay, and how did you reach that line?",
      "How do you help students show their own thinking, and how do you check what they truly understand, when an AI can produce a fluent answer instantly?",
      "How do you teach students to weigh evidence and different perspectives to reach an informed judgement when AI can provide an answer in seconds?",
      "How do you decide when to rely on an AI tool or a standardised metric, and when to override it?",
      "How do you translate high-level AI policy into guidance that is fair, age-appropriate, and ethical for your own students?",
      "How do you keep staff aligned on what responsible AI use looks like, so students get one consistent message?",
      "How can AI help colleagues who are new to IB or newly certified without replacing mentoring and human relationships?",
      "Think about a time when you led a conversation about a new technology with sceptical, tired, or anxious colleagues or parents. What helped?",
      "What is one small step you could take this term to use AI in a way that supports wellbeing as well as learning?"
    ]
  },
  "presets": {
    "E": "Host a Story Circle with my students or colleagues.",
    "P": "Arrange one informal meeting, such as a coffee or a walk, with a colleague from a different department, school, or culture, with no agenda beyond learning about their week.",
    "O": "Pick a real case study in AI in your subject or related industry, and discuss it with my students.",
    "C": "Redesign one routine lesson so students explore the topic through intercultural dialogue.",
    "H": "Pick one routine task that AI can help with, use it to free up thirty minutes, and spend that time on something that supports a student's or colleague's wellbeing.",
    "A": "Create space with students to discuss how AI affects their social dynamics and integration."
  }
};
